# Generated by Django 3.2.6 on 2022-01-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
