# Generated by Django 3.2.6 on 2022-01-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_game_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='path',
        ),
        migrations.AddField(
            model_name='game',
            name='html',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
