# Generated by Django 3.2.6 on 2022-01-30 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_users_games_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
