# Generated by Django 3.2.6 on 2022-01-31 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_users_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
    ]
