# Generated by Django 3.2.6 on 2022-02-03 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220203_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='stage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.stage'),
        ),
    ]
