# Generated by Django 3.2.6 on 2022-02-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_game_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='token',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
