# Generated by Django 3.2.6 on 2022-02-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_game_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
