# Generated by Django 3.2.6 on 2022-01-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220128_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('games_settings', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['name', 'time_create'], 'verbose_name': 'игра', 'verbose_name_plural': 'игры'},
        ),
        migrations.AlterField(
            model_name='game',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
