# Generated by Django 3.2.6 on 2022-01-30 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_users_games_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='games_settings',
        ),
    ]
