# Generated by Django 3.2.6 on 2022-01-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_users_games_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='games_settings',
            field=models.TextField(default='{}'),
        ),
    ]
