# Generated by Django 3.2.6 on 2022-01-30 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
